Repository nbortolotti/tflitego, pull requests merged in 2021-01, with the labels that each got.

#9 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation

#8 Improve docs
  README.md
Labels: documentation

#7 Improve naming convention on files
  errors.go
  interpreter.go
  model.go
  options.go
  tensor.go
  utils.go
  utils_test.go
Labels: enhancement

#14 Package name tflitego change for tflite
  README.md
  errors.go
  interpreter.go
  model.go
  options.go
  tensor.go
  utils.go
  utils_test.go
Labels: documentation, enhancement

#17 Use go modules
  go.mod
Labels: enhancement
